### ISSUE TITLE
Hey ik snap hier dus werkelijk niks van!

### ISSUE THREAD

**Issue by prootygames** [maxverbeek/magister-google-sync#1]
ik heb vrijwel geen ervaring met coderen maar ik wil heel graag mijn magister agenda syncen met mijn google agenda. Kun je er een video op maken of een gedetailleerde uitleg eli5 (explain like im five).

Dit wordt heel erg gewaardeerd

**Comment by maxverbeek** [comment]
Gezien ik kan begrijpen dat het compilen van dit project nogal moeilijk is, heb ik dat hier voor je gedaan. Ik heb zelf een client_secrets.json gemaakt, dus die kun je wel gebruiken. Pak dit [magister-google-sync-1.0.zip](https://github.com/skimmet/magister-google-sync/files/887232/magister-google-sync-1.0.zip) bestand uit, en voer dit commando uit in een CMD:
`java -jar magister-google-sync-1.0.jar`

Dan krijg je instructies, wat je precies moet invullen. Voor het geval je niet weet hoe een CMD werkt, zorg ervoor dat je CMD in de goede map zit. Dit kun je doen met het cd commando.

bijv.: Je prompt ziet er zo uit: `> C:\Users\skimmet` maar je bestand staat in `C:\Users\skimmet\Downloads` typ dan `cd Downloads` om naar de downloads map te gaan.

succes.

**Comment by prootygames** [comment]
Bedankt! Ik denk dat dit wel gaat lukken.
Mvg prooty
