### ISSUE TITLE
Kan qradle -r run niet runnen

### ISSUE THREAD

**Issue by MeesMaas** [maxverbeek/magister-google-sync#3]
```
FAILURE: Build failed with an exception.

* Where:
Build file '/home/mees/GitHub/magister-google-sync/build.gradle' line: 26

* What went wrong:
A problem occurred evaluating root project 'magister-google-sync'.
> Could not resolve all dependencies for configuration ':compile'.
   > Module version group:, module:magister-google-sync, version:1.0, configuration:compile declares a dependency on configuration 'default' which is not declared in the module descriptor for group:magister-google-sync, module:magister-api, version:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

```

**Comment by maxverbeek** [comment]
Weet je zeker dat je de submodule goed hebt gecloned?

```sh
git submodule init
git submodule update
```

Kijk voor de zekerheid of de directory `magister-api` niet leeg is. Mocht niks werken, dan kun je proberen om die API repo apart te clonen, en hem gewoon handmatig in die directory te zetten.

**Comment by MeesMaas** [comment]
welke repo is dat?

**Comment by maxverbeek** [comment]
https://github.com/Magister-Android/magister-api

**Comment by MeesMaas** [comment]
Krijg nog steeds diezelfde error.

**Comment by maxverbeek** [comment]
Heb net in issue #4 verandert hoe die repo wordt gedownload, zodat iedereen hem nu kan downloaden. Ook wil ik je er op wijzen dat je een `client_secret.json` bestand nodig hebt. In de readme staat hoe je dit kan downloaden.

**Comment by maxverbeek** [comment]
Het is mij immers ook gelukt om `gradle -q run` zonder fouten uit te voeren. Ik zit inmiddels niet meer op een school waar magister wordt gebruikt, dus ik weet niet meer zeker of de API werkt.
