### ISSUE TITLE
Permission Denied wanneer ik de git submodule update

### ISSUE THREAD

**Issue by broodroosterdev** [maxverbeek/magister-google-sync#4]
Wanneer ik na de `git submodule init` de `git submodule update` run krijg ik deze error: 

> Cloning into 'magister-api'...
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:Magister-Android/magister-api' into submodule path 'magister-api' failed

Hoe los ik dit op?

**Comment by maxverbeek** [comment]
Ah dat komt omdat die submodule gecloned wordt over ssh, en niet over
HTTPS. Je kan dit oplossen om in het .gitmodules bestand, die repo te
veranderen van git@github.com:blah/blah naar
https://github.com/Magister-Android/magister-api
